#
# Copyright (c) 2023 Airbyte, Inc., all rights reserved.
#

import base64
import logging
import os
import time
from calendar import monthrange
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from http import HTTPStatus
from importlib.metadata import PackageNotFoundError, version as package_version
from pathlib import Path
from threading import Lock
from typing import Any, Callable, ClassVar, Iterable, Mapping, Optional, Union
from urllib.parse import parse_qs, urlsplit

import requests
from requests import HTTPError

from airbyte_cdk.sources.declarative.auth.declarative_authenticator import NoAuth
from airbyte_cdk.sources.declarative.interpolation import InterpolatedString
from airbyte_cdk.sources.declarative.migrations.state_migration import StateMigration
from airbyte_cdk.sources.declarative.extractors.record_extractor import RecordExtractor
from airbyte_cdk.sources.declarative.requesters.http_requester import HttpRequester
from airbyte_cdk.sources.declarative.types import Config
from airbyte_cdk.sources.types import StreamSlice, StreamState

# https://developers.zoom.us/docs/internal-apps/s2s-oauth/#successful-response
# The Bearer token generated by server-to-server token will expire in one hour
BEARER_TOKEN_EXPIRES_IN = 3590

class SingletonMeta(type):
    _instances = {}

    def __call__(cls, *args, **kwargs):
        """
        Possible changes to the value of the `__init__` argument do not affect
        the returned instance.
        """
        if cls not in cls._instances:
            instance = super().__call__(*args, **kwargs)
            cls._instances[cls] = instance
        return cls._instances[cls]

@dataclass
class ServerToServerOauthAuthenticator(NoAuth):
    config: Config
    account_id: Union[InterpolatedString, str]
    client_id: Union[InterpolatedString, str]
    client_secret: Union[InterpolatedString, str]
    authorization_endpoint: Union[InterpolatedString, str]

    _instance = None
    _generate_token_time = 0
    _access_token = None
    _grant_type = "account_credentials"
    _token_lock: ClassVar[Lock] = Lock()

    def __post_init__(self, parameters: Mapping[str, Any]):
        self._account_id = InterpolatedString.create(self.account_id, parameters=parameters).eval(self.config)
        self._client_id = InterpolatedString.create(self.client_id, parameters=parameters).eval(self.config)
        self._client_secret = InterpolatedString.create(self.client_secret, parameters=parameters).eval(self.config)
        self._authorization_endpoint = InterpolatedString.create(self.authorization_endpoint, parameters=parameters).eval(self.config)

    def __call__(self, request: requests.PreparedRequest) -> requests.PreparedRequest:
        """Attach the page access token to params to authenticate on the HTTP request"""
        if self._access_token is None or ((time.time() - self._generate_token_time) > BEARER_TOKEN_EXPIRES_IN):
            with self._token_lock:
                if self._access_token is None or ((time.time() - self._generate_token_time) > BEARER_TOKEN_EXPIRES_IN):
                    self._access_token = self.generate_access_token()
        headers = {"Authorization": f"Bearer {self._access_token}", "Content-type": "application/json"}
        request.headers.update(headers)

        return request

    @property
    def auth_header(self) -> str:
        return "Authorization"

    @property
    def token(self) -> Optional[str]:
        return self._access_token if self._access_token else None

    def generate_access_token(self) -> str:
        self._generate_token_time = time.time()
        try:
            token = base64.b64encode(f"{self._client_id}:{self._client_secret}".encode("ascii")).decode("utf-8")
            headers = {"Authorization": f"Basic {token}", "Content-type": "application/json"}
            rest = requests.post(
                url=f"{self._authorization_endpoint}?grant_type={self._grant_type}&account_id={self._account_id}", headers=headers
            )
            if rest.status_code != HTTPStatus.OK:
                raise HTTPError(rest.text)
            return rest.json().get("access_token")
        except Exception as e:
            raise Exception(f"Error while generating access token: {e}") from e

@dataclass
class ZoomPhoneTranscriptStateMigration(StateMigration):
    """Repair transcript/timeline parent state for incremental parent traversal.

    The child cursor ``recording_date_time`` is copied directly from the
    ``phone_recordings.date_time`` parent record, so it is safe to use as the
    initial parent cursor when upgrading existing state that predates
    ``incremental_dependency: true``.
    """

    _logger: ClassVar[logging.Logger] = logging.getLogger("airbyte.phone_transcript_state")
    _parent_stream_name: ClassVar[str] = "phone_recordings"
    _parent_cursor_field: ClassVar[str] = "date_time"
    _child_cursor_field: ClassVar[str] = "recording_date_time"

    @classmethod
    def _candidate_parent_cursor(cls, stream_state: Mapping[str, Any]) -> tuple[Optional[Any], Optional[str]]:
        parent_state = stream_state.get("parent_state")
        if isinstance(parent_state, Mapping):
            phone_parent_state = parent_state.get(cls._parent_stream_name)
            if isinstance(phone_parent_state, Mapping):
                value = phone_parent_state.get(cls._parent_cursor_field)
                if value not in (None, ""):
                    return value, "parent_state"
                value = phone_parent_state.get(cls._child_cursor_field)
                if value not in (None, ""):
                    return value, "parent_state.recording_date_time"

        legacy_parent_state = stream_state.get(cls._parent_stream_name)
        if isinstance(legacy_parent_state, Mapping):
            value = legacy_parent_state.get(cls._parent_cursor_field)
            if value not in (None, ""):
                return value, "phone_recordings.date_time"
            value = legacy_parent_state.get(cls._child_cursor_field)
            if value not in (None, ""):
                return value, "phone_recordings.recording_date_time"

        global_state = stream_state.get("state")
        if isinstance(global_state, Mapping):
            value = global_state.get(cls._parent_cursor_field)
            if value not in (None, ""):
                return value, "state.date_time"
            value = global_state.get(cls._child_cursor_field)
            if value not in (None, ""):
                return value, "state.recording_date_time"

        value = stream_state.get(cls._parent_cursor_field)
        if value not in (None, ""):
            return value, "date_time"

        value = stream_state.get(cls._child_cursor_field)
        if value not in (None, ""):
            return value, "recording_date_time"

        return None, None

    @classmethod
    def _has_valid_parent_state(cls, stream_state: Mapping[str, Any]) -> bool:
        parent_state = stream_state.get("parent_state")
        if not isinstance(parent_state, Mapping):
            return False
        phone_parent_state = parent_state.get(cls._parent_stream_name)
        return (
            isinstance(phone_parent_state, Mapping)
            and phone_parent_state.get(cls._parent_cursor_field) not in (None, "")
        )

    def should_migrate(self, stream_state: Mapping[str, Any]) -> bool:
        if not stream_state or self._has_valid_parent_state(stream_state):
            return False
        cursor_value, _ = self._candidate_parent_cursor(stream_state)
        return cursor_value not in (None, "")

    def migrate(self, stream_state: Mapping[str, Any]) -> Mapping[str, Any]:
        cursor_value, source = self._candidate_parent_cursor(stream_state)
        if cursor_value in (None, ""):
            return stream_state

        migrated = dict(stream_state)
        existing_parent_state = migrated.get("parent_state")
        parent_state = dict(existing_parent_state) if isinstance(existing_parent_state, Mapping) else {}
        existing_phone_state = parent_state.get(self._parent_stream_name)
        phone_state = dict(existing_phone_state) if isinstance(existing_phone_state, Mapping) else {}
        phone_state[self._parent_cursor_field] = cursor_value
        parent_state[self._parent_stream_name] = phone_state
        migrated["parent_state"] = parent_state

        self._logger.info(
            "[phone_transcript_state] repaired_parent_state "
            f"parent={self._parent_stream_name} source={source} cursor={cursor_value}"
        )
        return migrated

@dataclass
class TimelineRecordExtractor(RecordExtractor):
    """Extract timeline entries from the cached transcript response."""

    config: Config

    def extract_records(self, response: requests.Response) -> Iterable[Mapping[str, Any]]:
        try:
            payload = response.json()
        except (TypeError, ValueError):
            return

        if isinstance(payload, list):
            timeline = payload
        elif isinstance(payload, Mapping):
            timeline = payload.get("timeline")
        else:
            return

        if not isinstance(timeline, list):
            return

        for item in timeline:
            if isinstance(item, Mapping):
                yield dict(item)

@dataclass
class _ZoomPhoneRequestStats:
    """Process-wide request counters shared by concurrent requester instances."""

    started: int = 0
    completed: int = 0
    active: int = 0
    cache_hits: int = 0
    failures: int = 0
    total_duration_ms: int = 0
    last_status: Optional[int] = None
    last_from: Optional[str] = None
    last_to: Optional[str] = None
    last_summary_at: float = 0.0

@dataclass
class ZoomPhoneLoggingRequester(HttpRequester):
    """Zoom Phone requester with concise Airbyte-native INFO progress logging.

    Normal activity is summarized every 200 completed requests. Embedded
    ``phone_recordings`` parent traversal also emits a start message and, while
    it remains active, at most one progress summary per minute. Abnormal HTTP
    responses are logged immediately.
    """

    rate_limit_category: str = "UNKNOWN"
    history_limit_months: Optional[int] = None
    requester_role: str = "default"
    cache_name: Optional[str] = None

    _summary_every: ClassVar[int] = 200
    _parent_summary_interval_seconds: ClassVar[int] = 60
    _request_stats: ClassVar[dict[tuple[str, str], _ZoomPhoneRequestStats]] = {}
    _request_stats_lock: ClassVar[Lock] = Lock()
    _runtime_version_logged: ClassVar[bool] = False
    _runtime_version_lock: ClassVar[Lock] = Lock()
    _rate_limit_configs_logged: ClassVar[set[tuple[str, str, str]]] = set()
    _rate_limit_config_lock: ClassVar[Lock] = Lock()

    def __post_init__(self, parameters: Mapping[str, Any]) -> None:
        display_name = self.name
        cache_key = self.cache_name or display_name

        # HttpRequester uses its name only as the native HTTP cache namespace.
        # Temporarily use cache_key while HttpRequester creates its HttpClient,
        # then restore the real stream name for readable logs.
        self.name = cache_key
        try:
            super().__post_init__(parameters)
        finally:
            self.name = display_name

        self._log_runtime_configuration_once()
        self._log_rate_limit_configuration_once()
        self._warn_if_history_window_exceeded()

    @property
    def _stats_key(self) -> tuple[str, str]:
        return self.name, self.requester_role

    def _get_stats(self) -> _ZoomPhoneRequestStats:
        with self._request_stats_lock:
            stats = self._request_stats.get(self._stats_key)
            if stats is None:
                stats = _ZoomPhoneRequestStats()
                self._request_stats[self._stats_key] = stats
            return stats

    @staticmethod
    def _request_dates(response: requests.Response) -> tuple[Optional[str], Optional[str]]:
        request = getattr(response, "request", None)
        url = getattr(request, "url", None)
        if not url:
            return None, None
        query = parse_qs(urlsplit(url).query)
        request_from = query.get("from", [None])[-1]
        request_to = query.get("to", [None])[-1]
        return request_from, request_to

    def _log_summary(self) -> None:
        stats = self._get_stats()
        now = time.monotonic()
        with self._request_stats_lock:
            started = stats.started
            completed = stats.completed
            active = stats.active
            cache_hits = stats.cache_hits
            failures = stats.failures
            total_duration_ms = stats.total_duration_ms
            last_status = stats.last_status
            last_from = stats.last_from
            last_to = stats.last_to
            stats.last_summary_at = now

        avg_ms = round(total_duration_ms / completed) if completed else 0
        cache_rate = (cache_hits / completed) * 100 if completed else 0.0
        fields = [
            f"[{self.name}]",
            f"role={self.requester_role}",
            f"requests={completed}",
            f"started={started}",
            f"active={active}",
            f"avg_ms={avg_ms}",
            f"cache_hits={cache_hits}",
            f"cache={cache_rate:.1f}%",
            f"failures={failures}",
        ]
        if last_status is not None:
            fields.append(f"last_status={last_status}")
        if last_from is not None:
            fields.append(f"last_from={last_from}")
        if last_to is not None:
            fields.append(f"last_to={last_to}")

        self.logger.info(" ".join(fields))

    def _log_parent_start(self) -> None:
        self.logger.info(
            f"[{self.name}] role={self.requester_role} parent_fetch=start"
        )

    def send_request(
        self,
        stream_state: Optional[StreamState] = None,
        stream_slice: Optional[StreamSlice] = None,
        next_page_token: Optional[Mapping[str, Any]] = None,
        path: Optional[str] = None,
        request_headers: Optional[Mapping[str, Any]] = None,
        request_params: Optional[Mapping[str, Any]] = None,
        request_body_data: Optional[Union[Mapping[str, Any], str]] = None,
        request_body_json: Optional[Mapping[str, Any]] = None,
        log_formatter: Optional[Callable[[requests.Response], Any]] = None,
    ) -> Optional[requests.Response]:
        stats = self._get_stats()
        with self._request_stats_lock:
            stats.started += 1
            started_count = stats.started
            stats.active += 1

        if self.requester_role == "transcript_parent" and started_count == 1:
            self._log_parent_start()

        started_at = time.monotonic()
        try:
            response = super().send_request(
                stream_state=stream_state,
                stream_slice=stream_slice,
                next_page_token=next_page_token,
                path=path,
                request_headers=request_headers,
                request_params=request_params,
                request_body_data=request_body_data,
                request_body_json=request_body_json,
                log_formatter=log_formatter,
            )
        except Exception as exc:
            duration_ms = round((time.monotonic() - started_at) * 1000)
            with self._request_stats_lock:
                stats.active = max(0, stats.active - 1)
                stats.failures += 1
                stats.total_duration_ms += duration_ms

            self.logger.warning(
                f"Failed [{self.name}] role={self.requester_role} "
                f"category={self.rate_limit_category} duration_ms={duration_ms} "
                f"error={type(exc).__name__}"
            )
            raise

        duration_ms = round((time.monotonic() - started_at) * 1000)
        if response is None:
            with self._request_stats_lock:
                stats.active = max(0, stats.active - 1)
                stats.failures += 1
                stats.total_duration_ms += duration_ms
            self.logger.warning(
                f"Failed [{self.name}] role={self.requester_role} "
                f"category={self.rate_limit_category} duration_ms={duration_ms} response=None"
            )
            return None

        request_from, request_to = self._request_dates(response)
        from_cache = bool(getattr(response, "from_cache", False))
        now = time.monotonic()
        with self._request_stats_lock:
            stats.completed += 1
            completed_count = stats.completed
            stats.active = max(0, stats.active - 1)
            stats.total_duration_ms += duration_ms
            stats.last_status = response.status_code
            if from_cache:
                stats.cache_hits += 1
            if request_from is not None:
                stats.last_from = request_from
            if request_to is not None:
                stats.last_to = request_to
            parent_summary_due = (
                self.requester_role == "transcript_parent"
                and now - stats.last_summary_at >= self._parent_summary_interval_seconds
            )

        if parent_summary_due or completed_count % self._summary_every == 0:
            self._log_summary()

        if response.status_code == HTTPStatus.TOO_MANY_REQUESTS or response.status_code >= 500:
            self.logger.warning(
                f"Response [{self.name}] role={self.requester_role} "
                f"category={self.rate_limit_category} status={response.status_code} "
                f"duration_ms={duration_ms} cache_hit={from_cache}"
            )

        return response

    @staticmethod
    def _months_ago(months: int) -> date:
        today = datetime.now(timezone.utc).date()
        month_index = today.year * 12 + today.month - 1 - months
        year, zero_based_month = divmod(month_index, 12)
        month = zero_based_month + 1
        day = min(today.day, monthrange(year, month)[1])
        return date(year, month, day)

    def _log_runtime_configuration_once(self) -> None:
        if ZoomPhoneLoggingRequester._runtime_version_logged:
            return

        with ZoomPhoneLoggingRequester._runtime_version_lock:
            if ZoomPhoneLoggingRequester._runtime_version_logged:
                return
            try:
                cdk_version = package_version("airbyte-cdk")
            except PackageNotFoundError:
                cdk_version = "unknown"

            configured_workers = self.config.get("num_workers", 20)
            light_rps = self.config.get("phone_light_requests_per_second", 20)
            medium_rps = self.config.get("phone_medium_requests_per_second", 10)
            heavy_rps = self.config.get("phone_heavy_requests_per_second", 5)
            heavy_per_day = self.config.get("phone_heavy_requests_per_day", 15000)
            self.logger.info(f"Runtime cdk={cdk_version} workers={configured_workers}")
            self.logger.info(
                "API budget "
                f"light={light_rps}/s "
                f"medium={medium_rps}/s "
                f"heavy={heavy_rps}/s "
                f"heavy_day={heavy_per_day}/day"
            )
            ZoomPhoneLoggingRequester._runtime_version_logged = True

    def _log_rate_limit_configuration_once(self) -> None:
        key = (self.name, self.requester_role, self.rate_limit_category)
        with ZoomPhoneLoggingRequester._rate_limit_config_lock:
            if key in ZoomPhoneLoggingRequester._rate_limit_configs_logged:
                return
            self.logger.info(
                f"RateLimit [{self.name}] role={self.requester_role} category={self.rate_limit_category}"
            )
            ZoomPhoneLoggingRequester._rate_limit_configs_logged.add(key)

    def _warn_if_history_window_exceeded(self) -> None:
        if self.history_limit_months is None:
            return

        configured_start = self.config.get("phone_start_date")
        if not configured_start:
            return

        try:
            requested_start = date.fromisoformat(str(configured_start))
        except (TypeError, ValueError):
            return

        earliest_start = self._months_ago(self.history_limit_months) + timedelta(days=1)
        if requested_start < earliest_start:
            self.logger.warning(
                f"Notice [{self.name}] "
                f"requested_phone_start_date={requested_start.isoformat()} "
                f"exceeds_zoom_history_window={self.history_limit_months}m "
                f"effective_start_date={earliest_start.isoformat()}"
            )

@dataclass
class ZoomPhoneCachedRequester(ZoomPhoneLoggingRequester):
    """Zoom Phone requester using Airbyte's native SQLite HTTP cache on disk.

    Airbyte falls back to an in-memory cache when ``REQUEST_CACHE_PATH`` is not
    set. A per-job temporary disk cache is preferable here because transcript
    and timeline are separate serialized streams that intentionally reuse the
    exact same transcript-download responses.
    """

    use_cache: bool = True

    _default_cache_dir: ClassVar[str] = "/tmp/airbyte-request-cache"
    _cache_configs_logged: ClassVar[set[tuple[str, str]]] = set()
    _cache_config_lock: ClassVar[Lock] = Lock()

    def __post_init__(self, parameters: Mapping[str, Any]) -> None:
        cache_dir = os.environ.get("REQUEST_CACHE_PATH") or self._default_cache_dir
        os.environ.setdefault("REQUEST_CACHE_PATH", cache_dir)
        Path(cache_dir).mkdir(parents=True, exist_ok=True)

        self.use_cache = True
        super().__post_init__(parameters)

        cache_key = self.cache_name or self.name
        log_key = (cache_key, cache_dir)
        with self._cache_config_lock:
            if log_key not in self._cache_configs_logged:
                self.logger.info(
                    f"Cache [{self.name}] namespace={cache_key} backend=sqlite path={cache_dir}"
                )
                self._cache_configs_logged.add(log_key)
