#
# Copyright (c) 2023 Airbyte, Inc., all rights reserved.
#

import base64
import logging
import re
import time
from calendar import monthrange
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta, timezone
from http import HTTPStatus
from importlib.metadata import PackageNotFoundError, version as package_version
from threading import Lock, Thread
from typing import Any, Callable, ClassVar, Iterable, Mapping, Optional, Tuple, Union
from urllib.parse import urlsplit

import requests
from requests import HTTPError

from airbyte_cdk.models import Level
from airbyte_cdk.sources.declarative.auth.declarative_authenticator import NoAuth
from airbyte_cdk.sources.declarative.interpolation import InterpolatedString
from airbyte_cdk.sources.declarative.migrations.state_migration import StateMigration
from airbyte_cdk.sources.declarative.extractors.record_extractor import RecordExtractor
from airbyte_cdk.sources.declarative.partition_routers.substream_partition_router import SafeResponse
from airbyte_cdk.sources.declarative.requesters.http_requester import HttpRequester
from airbyte_cdk.sources.streams.http import HttpClient
from airbyte_cdk.sources.declarative.types import Config


# https://developers.zoom.us/docs/internal-apps/s2s-oauth/#successful-response
# The Bearer token generated by server-to-server token will expire in one hour
BEARER_TOKEN_EXPIRES_IN = 3590



class SingletonMeta(type):
    _instances = {}

    def __call__(cls, *args, **kwargs):
        """
        Possible changes to the value of the `__init__` argument do not affect
        the returned instance.
        """
        if cls not in cls._instances:
            instance = super().__call__(*args, **kwargs)
            cls._instances[cls] = instance
        return cls._instances[cls]


@dataclass
class ServerToServerOauthAuthenticator(NoAuth):
    config: Config
    account_id: Union[InterpolatedString, str]
    client_id: Union[InterpolatedString, str]
    client_secret: Union[InterpolatedString, str]
    authorization_endpoint: Union[InterpolatedString, str]

    _instance = None
    _generate_token_time = 0
    _access_token = None
    _grant_type = "account_credentials"
    _token_lock: ClassVar[Lock] = Lock()

    def __post_init__(self, parameters: Mapping[str, Any]):
        self._account_id = InterpolatedString.create(self.account_id, parameters=parameters).eval(self.config)
        self._client_id = InterpolatedString.create(self.client_id, parameters=parameters).eval(self.config)
        self._client_secret = InterpolatedString.create(self.client_secret, parameters=parameters).eval(self.config)
        self._authorization_endpoint = InterpolatedString.create(self.authorization_endpoint, parameters=parameters).eval(self.config)

    def __call__(self, request: requests.PreparedRequest) -> requests.PreparedRequest:
        """Attach the page access token to params to authenticate on the HTTP request"""
        if self._access_token is None or ((time.time() - self._generate_token_time) > BEARER_TOKEN_EXPIRES_IN):
            with self._token_lock:
                if self._access_token is None or ((time.time() - self._generate_token_time) > BEARER_TOKEN_EXPIRES_IN):
                    self._access_token = self.generate_access_token()
        headers = {"Authorization": f"Bearer {self._access_token}", "Content-type": "application/json"}
        request.headers.update(headers)

        return request

    @property
    def auth_header(self) -> str:
        return "Authorization"

    @property
    def token(self) -> Optional[str]:
        return self._access_token if self._access_token else None

    def generate_access_token(self) -> str:
        self._generate_token_time = time.time()
        try:
            token = base64.b64encode(f"{self._client_id}:{self._client_secret}".encode("ascii")).decode("utf-8")
            headers = {"Authorization": f"Basic {token}", "Content-type": "application/json"}
            rest = requests.post(
                url=f"{self._authorization_endpoint}?grant_type={self._grant_type}&account_id={self._account_id}", headers=headers
            )
            if rest.status_code != HTTPStatus.OK:
                raise HTTPError(rest.text)
            return rest.json().get("access_token")
        except Exception as e:
            raise Exception(f"Error while generating access token: {e}") from e



@dataclass
class ZoomPhoneTranscriptStateMigration(StateMigration):
    """Repair transcript/timeline parent state for incremental parent traversal.

    The child cursor ``recording_date_time`` is copied directly from the
    ``phone_recordings.date_time`` parent record, so it is safe to use as the
    initial parent cursor when upgrading existing state that predates
    ``incremental_dependency: true``.
    """

    _logger: ClassVar[logging.Logger] = logging.getLogger("airbyte.phone_transcript_state")
    _parent_stream_name: ClassVar[str] = "phone_recordings"
    _parent_cursor_field: ClassVar[str] = "date_time"
    _child_cursor_field: ClassVar[str] = "recording_date_time"

    @classmethod
    def _candidate_parent_cursor(cls, stream_state: Mapping[str, Any]) -> tuple[Optional[Any], Optional[str]]:
        parent_state = stream_state.get("parent_state")
        if isinstance(parent_state, Mapping):
            phone_parent_state = parent_state.get(cls._parent_stream_name)
            if isinstance(phone_parent_state, Mapping):
                value = phone_parent_state.get(cls._parent_cursor_field)
                if value not in (None, ""):
                    return value, "parent_state"
                value = phone_parent_state.get(cls._child_cursor_field)
                if value not in (None, ""):
                    return value, "parent_state.recording_date_time"

        legacy_parent_state = stream_state.get(cls._parent_stream_name)
        if isinstance(legacy_parent_state, Mapping):
            value = legacy_parent_state.get(cls._parent_cursor_field)
            if value not in (None, ""):
                return value, "phone_recordings.date_time"
            value = legacy_parent_state.get(cls._child_cursor_field)
            if value not in (None, ""):
                return value, "phone_recordings.recording_date_time"

        global_state = stream_state.get("state")
        if isinstance(global_state, Mapping):
            value = global_state.get(cls._parent_cursor_field)
            if value not in (None, ""):
                return value, "state.date_time"
            value = global_state.get(cls._child_cursor_field)
            if value not in (None, ""):
                return value, "state.recording_date_time"

        value = stream_state.get(cls._parent_cursor_field)
        if value not in (None, ""):
            return value, "date_time"

        value = stream_state.get(cls._child_cursor_field)
        if value not in (None, ""):
            return value, "recording_date_time"

        return None, None

    @classmethod
    def _has_valid_parent_state(cls, stream_state: Mapping[str, Any]) -> bool:
        parent_state = stream_state.get("parent_state")
        if not isinstance(parent_state, Mapping):
            return False
        phone_parent_state = parent_state.get(cls._parent_stream_name)
        return (
            isinstance(phone_parent_state, Mapping)
            and phone_parent_state.get(cls._parent_cursor_field) not in (None, "")
        )

    def should_migrate(self, stream_state: Mapping[str, Any]) -> bool:
        if not stream_state or self._has_valid_parent_state(stream_state):
            return False
        cursor_value, _ = self._candidate_parent_cursor(stream_state)
        return cursor_value not in (None, "")

    def migrate(self, stream_state: Mapping[str, Any]) -> Mapping[str, Any]:
        cursor_value, source = self._candidate_parent_cursor(stream_state)
        if cursor_value in (None, ""):
            return stream_state

        migrated = dict(stream_state)
        existing_parent_state = migrated.get("parent_state")
        parent_state = dict(existing_parent_state) if isinstance(existing_parent_state, Mapping) else {}
        existing_phone_state = parent_state.get(self._parent_stream_name)
        phone_state = dict(existing_phone_state) if isinstance(existing_phone_state, Mapping) else {}
        phone_state[self._parent_cursor_field] = cursor_value
        parent_state[self._parent_stream_name] = phone_state
        migrated["parent_state"] = parent_state

        self._logger.info(
            "[phone_transcript_state] repaired_parent_state "
            f"parent={self._parent_stream_name} source={source} cursor={cursor_value}"
        )
        return migrated


@dataclass
class TimelineRecordExtractor(RecordExtractor):
    """Extract timeline entries and report whether Airbyte used lazy, cached HTTP, or network HTTP."""

    config: Config
    _summary_every: ClassVar[int] = 1000
    _logger: ClassVar[logging.Logger] = logging.getLogger("airbyte.phone_recording_transcript_timeline")
    _path_lock: Lock = field(default_factory=Lock, init=False, repr=False)
    _response_count: int = field(default=0, init=False, repr=False)
    _lazy_count: int = field(default=0, init=False, repr=False)
    _http_cache_count: int = field(default=0, init=False, repr=False)
    _http_network_count: int = field(default=0, init=False, repr=False)

    def _record_source_path(self, response: requests.Response) -> None:
        if isinstance(response, SafeResponse):
            source_path = "lazy"
        elif bool(getattr(response, "from_cache", False)):
            source_path = "http_cache"
        else:
            source_path = "http_network"

        summary = None
        with self._path_lock:
            self._response_count += 1
            if source_path == "lazy":
                self._lazy_count += 1
            elif source_path == "http_cache":
                self._http_cache_count += 1
            else:
                self._http_network_count += 1

            if self._response_count % self._summary_every == 0:
                summary = (
                    self._response_count,
                    self._lazy_count,
                    self._http_cache_count,
                    self._http_network_count,
                )

        if summary is not None:
            response_count, lazy_count, http_cache_count, http_network_count = summary
            lazy_pct = (lazy_count / response_count) * 100
            self._logger.info(
                "[phone_recording_transcript_timeline] "
                f"source_responses={response_count} "
                f"lazy={lazy_count} "
                f"http_cache={http_cache_count} "
                f"http_network={http_network_count} "
                f"lazy_pct={lazy_pct:.1f}%"
            )

    def extract_records(self, response: requests.Response) -> Iterable[Mapping[str, Any]]:
        self._record_source_path(response)

        try:
            payload = response.json()
        except (TypeError, ValueError):
            return

        if isinstance(payload, list):
            timeline = payload
        elif isinstance(payload, Mapping):
            timeline = payload.get("timeline")
        else:
            return

        if not isinstance(timeline, list):
            return

        for item in timeline:
            if isinstance(item, Mapping):
                yield dict(item)


@dataclass
class _ZoomPhoneHttpMetrics:
    """Process-wide HTTP metrics shared by concurrent requester/client instances."""

    lock: Lock = field(default_factory=Lock, repr=False)
    started: int = 0
    completed: int = 0
    active: int = 0
    cache_hits: int = 0
    failures: int = 0
    total_duration_ms: int = 0
    last_activity_monotonic: float = field(default_factory=time.monotonic)
    last_status: Optional[int] = None
    last_from: Optional[str] = None
    last_to: Optional[str] = None
    heartbeat_started: bool = False


class ZoomPhoneHttpClient(HttpClient):
    """Single HTTP observability point for every Zoom Phone logical request.

    All Phone requesters instantiate this client. Metrics are process-wide and keyed
    by (stream name, requester role), so concurrent component copies cannot split the
    counters and hide progress. The underlying Airbyte HttpClient still owns request
    preparation, caching, API budgets, retries, authentication, and error handling.
    """

    _summary_every: ClassVar[int] = 200
    _heartbeat_interval_seconds: ClassVar[int] = 300
    _heartbeat_idle_grace_intervals: ClassVar[int] = 12
    _registry: ClassVar[dict[tuple[str, str], _ZoomPhoneHttpMetrics]] = {}
    _registry_lock: ClassVar[Lock] = Lock()

    def __init__(
        self,
        *,
        display_name: str,
        requester_role: str,
        rate_limit_category: str,
        **kwargs: Any,
    ) -> None:
        self._display_name = display_name
        self._requester_role = requester_role
        self._rate_limit_category = rate_limit_category
        super().__init__(**kwargs)

    @property
    def _metrics_key(self) -> tuple[str, str]:
        return self._display_name, self._requester_role

    def _metrics(self) -> _ZoomPhoneHttpMetrics:
        key = self._metrics_key
        with self._registry_lock:
            metrics = self._registry.get(key)
            if metrics is None:
                metrics = _ZoomPhoneHttpMetrics()
                self._registry[key] = metrics
            return metrics

    @staticmethod
    def _safe_endpoint(url: str) -> str:
        path = urlsplit(url).path
        return re.sub(
            r"(/v2/phone/recording_transcript/download/)[^/]+$",
            r"\1{recording_id}",
            path,
        )

    def _emit(self, level: Level, message: str) -> None:
        # Custom requesters are not guaranteed to receive Airbyte's live
        # message repository. Use the HttpClient logger directly; this is the
        # same logger path already proven to surface requester configuration
        # messages from concurrent parent reads.
        if level in (Level.ERROR, Level.FATAL):
            self._logger.error(message)
        elif level == Level.WARN:
            self._logger.warning(message)
        else:
            self._logger.info(message)

    def _snapshot(self) -> tuple[int, int, int, int, int, int, float, Optional[int], Optional[str], Optional[str]]:
        metrics = self._metrics()
        with metrics.lock:
            return (
                metrics.started,
                metrics.completed,
                metrics.active,
                metrics.cache_hits,
                metrics.failures,
                metrics.total_duration_ms,
                metrics.last_activity_monotonic,
                metrics.last_status,
                metrics.last_from,
                metrics.last_to,
            )

    def _emit_summary(self, *, heartbeat: bool = False) -> None:
        (
            started,
            completed,
            active,
            cache_hits,
            failures,
            total_duration_ms,
            last_activity_monotonic,
            last_status,
            last_from,
            last_to,
        ) = self._snapshot()

        avg_ms = round(total_duration_ms / completed) if completed else 0
        cache_rate = (cache_hits / completed) * 100 if completed else 0.0
        fields = [
            f"[{self._display_name}]",
            *(["(heartbeat)"] if heartbeat else []),
            f"role={self._requester_role}",
            f"requests={completed}",
            f"started={started}",
            f"active={active}",
            f"avg_ms={avg_ms}",
            f"cache_hits={cache_hits}",
            f"cache={cache_rate:.1f}%",
            f"failures={failures}",
        ]

        if heartbeat:
            fields.append(f"idle_s={max(0, round(time.monotonic() - last_activity_monotonic))}")

        if last_status is not None:
            fields.append(f"last_status={last_status}")
        if last_from is not None:
            fields.append(f"last_from={last_from}")
        if last_to is not None:
            fields.append(f"last_to={last_to}")

        self._emit(Level.INFO, " ".join(fields))

    def _heartbeat_loop(self) -> None:
        metrics = self._metrics()
        while True:
            time.sleep(self._heartbeat_interval_seconds)
            with metrics.lock:
                started = metrics.started
                active = metrics.active
                last_activity = metrics.last_activity_monotonic

            if started == 0:
                continue

            idle_seconds = time.monotonic() - last_activity
            idle_grace_seconds = self._heartbeat_interval_seconds * self._heartbeat_idle_grace_intervals
            if active == 0 and idle_seconds > idle_grace_seconds:
                continue

            self._emit_summary(heartbeat=True)

    def _ensure_heartbeat_started(self) -> None:
        metrics = self._metrics()
        with metrics.lock:
            if metrics.heartbeat_started:
                return
            metrics.heartbeat_started = True

        Thread(
            target=self._heartbeat_loop,
            name=f"zoom-http-heartbeat-{self._display_name}-{self._requester_role}",
            daemon=True,
        ).start()

    def send_request(
        self,
        http_method: str,
        url: str,
        request_kwargs: Mapping[str, Any],
        headers: Optional[Mapping[str, str]] = None,
        params: Optional[Mapping[str, str]] = None,
        json: Optional[Mapping[str, Any]] = None,
        data: Optional[Union[str, Mapping[str, Any]]] = None,
        dedupe_query_params: bool = False,
        log_formatter: Optional[Callable[[requests.Response], Any]] = None,
        exit_on_rate_limit: Optional[bool] = False,
    ) -> Tuple[requests.PreparedRequest, requests.Response]:
        metrics = self._metrics()
        request_from = str(params.get("from")) if params and params.get("from") is not None else None
        request_to = str(params.get("to")) if params and params.get("to") is not None else None

        with metrics.lock:
            metrics.started += 1
            started_count = metrics.started
            metrics.active += 1
            metrics.last_activity_monotonic = time.monotonic()
            if request_from is not None:
                metrics.last_from = request_from
            if request_to is not None:
                metrics.last_to = request_to

        self._ensure_heartbeat_started()

        if self._requester_role == "transcript_parent" and started_count == 1:
            fields = [
                f"[{self._display_name}]",
                "role=transcript_parent",
                "http=start",
            ]
            if request_from is not None:
                fields.append(f"from={request_from}")
            if request_to is not None:
                fields.append(f"to={request_to}")
            self._emit(Level.INFO, " ".join(fields))

        started_at = time.monotonic()
        try:
            request, response = super().send_request(
                http_method=http_method,
                url=url,
                request_kwargs=request_kwargs,
                headers=headers,
                params=params,
                json=json,
                data=data,
                dedupe_query_params=dedupe_query_params,
                log_formatter=log_formatter,
                exit_on_rate_limit=exit_on_rate_limit,
            )
        except Exception as exc:
            duration_ms = round((time.monotonic() - started_at) * 1000)
            with metrics.lock:
                metrics.completed += 1
                completed_count = metrics.completed
                metrics.active = max(0, metrics.active - 1)
                metrics.failures += 1
                metrics.total_duration_ms += duration_ms
                metrics.last_activity_monotonic = time.monotonic()

            self._emit(
                Level.WARN,
                f"Failed [{self._display_name}] "
                f"role={self._requester_role} "
                f"method={http_method} "
                f"endpoint={self._safe_endpoint(url)} "
                f"category={self._rate_limit_category} "
                f"duration_ms={duration_ms} "
                f"error={type(exc).__name__}",
            )
            if completed_count % self._summary_every == 0:
                self._emit_summary()
            raise

        duration_ms = round((time.monotonic() - started_at) * 1000)
        from_cache = bool(getattr(response, "from_cache", False))
        with metrics.lock:
            metrics.completed += 1
            completed_count = metrics.completed
            metrics.active = max(0, metrics.active - 1)
            metrics.total_duration_ms += duration_ms
            metrics.last_activity_monotonic = time.monotonic()
            metrics.last_status = response.status_code
            if from_cache:
                metrics.cache_hits += 1

        if response.status_code == HTTPStatus.TOO_MANY_REQUESTS or response.status_code >= 500:
            self._emit(
                Level.WARN,
                f"Response [{self._display_name}] "
                f"role={self._requester_role} "
                f"method={http_method} "
                f"endpoint={self._safe_endpoint(url)} "
                f"category={self._rate_limit_category} "
                f"status={response.status_code} "
                f"duration_ms={duration_ms} "
                f"cache_hit={from_cache}",
            )

        if self._requester_role == "transcript_parent" and completed_count == 1:
            self._emit_summary()
        elif completed_count % self._summary_every == 0:
            self._emit_summary()

        return request, response


@dataclass
class ZoomPhoneLoggingRequester(HttpRequester):
    """Zoom Phone requester backed by the observable ZoomPhoneHttpClient."""

    rate_limit_category: str = "UNKNOWN"
    history_limit_months: Optional[int] = None
    requester_role: str = "default"
    cache_name: Optional[str] = None

    _runtime_version_logged: ClassVar[bool] = False
    _runtime_version_lock: ClassVar[Lock] = Lock()
    _rate_limit_configs_logged: ClassVar[set[tuple[str, str, str]]] = set()
    _rate_limit_config_lock: ClassVar[Lock] = Lock()

    def __post_init__(self, parameters: Mapping[str, Any]) -> None:
        display_name = self.name
        cache_key = self.cache_name or display_name

        # HttpRequester has no client factory hook in CDK 7.28.3, so initialize
        # its standard fields first, then replace only the client implementation.
        self.name = cache_key
        try:
            super().__post_init__(parameters)
        finally:
            self.name = display_name

        backoff_strategies = (
            self.error_handler.backoff_strategies
            if self.error_handler is not None and hasattr(self.error_handler, "backoff_strategies")
            else None
        )
        self._http_client = ZoomPhoneHttpClient(
            name=cache_key,
            display_name=display_name,
            requester_role=self.requester_role,
            rate_limit_category=self.rate_limit_category,
            logger=self.logger,
            error_handler=self.error_handler,
            api_budget=self.api_budget,
            authenticator=self._authenticator,
            use_cache=self.use_cache,
            backoff_strategy=backoff_strategies,
            disable_retries=self.disable_retries,
            message_repository=self.message_repository,
        )

        self._log_runtime_configuration_once()
        self._log_rate_limit_configuration_once()
        self._warn_if_history_window_exceeded()

    @staticmethod
    def _months_ago(months: int) -> date:
        today = datetime.now(timezone.utc).date()
        month_index = today.year * 12 + today.month - 1 - months
        year, zero_based_month = divmod(month_index, 12)
        month = zero_based_month + 1
        day = min(today.day, monthrange(year, month)[1])
        return date(year, month, day)

    def _log_runtime_configuration_once(self) -> None:
        if ZoomPhoneLoggingRequester._runtime_version_logged:
            return

        with ZoomPhoneLoggingRequester._runtime_version_lock:
            if ZoomPhoneLoggingRequester._runtime_version_logged:
                return
            try:
                cdk_version = package_version("airbyte-cdk")
            except PackageNotFoundError:
                cdk_version = "unknown"

            configured_workers = self.config.get("num_workers", 20)
            light_rps = self.config.get("phone_light_requests_per_second", 20)
            medium_rps = self.config.get("phone_medium_requests_per_second", 10)
            heavy_rps = self.config.get("phone_heavy_requests_per_second", 5)
            heavy_per_day = self.config.get("phone_heavy_requests_per_day", 15000)
            self.logger.info(f"Runtime cdk={cdk_version} workers={configured_workers}")
            self.logger.info(
                "API budget "
                f"light={light_rps}/s "
                f"medium={medium_rps}/s "
                f"heavy={heavy_rps}/s "
                f"heavy_day={heavy_per_day}/day"
            )
            ZoomPhoneLoggingRequester._runtime_version_logged = True

    def _log_rate_limit_configuration_once(self) -> None:
        key = (self.name, self.requester_role, self.rate_limit_category)
        with ZoomPhoneLoggingRequester._rate_limit_config_lock:
            if key in ZoomPhoneLoggingRequester._rate_limit_configs_logged:
                return
            self.logger.info(
                f"RateLimit [{self.name}] role={self.requester_role} category={self.rate_limit_category}"
            )
            ZoomPhoneLoggingRequester._rate_limit_configs_logged.add(key)

    def _warn_if_history_window_exceeded(self) -> None:
        if self.history_limit_months is None:
            return

        configured_start = self.config.get("phone_start_date")
        if not configured_start:
            return

        try:
            requested_start = date.fromisoformat(str(configured_start))
        except (TypeError, ValueError):
            return

        earliest_start = self._months_ago(self.history_limit_months) + timedelta(days=1)
        if requested_start < earliest_start:
            self.logger.warning(
                f"Notice [{self.name}] "
                f"requested_phone_start_date={requested_start.isoformat()} "
                f"exceeds_zoom_history_window={self.history_limit_months}m "
                f"effective_start_date={earliest_start.isoformat()}"
            )


@dataclass
class ZoomPhoneCachedRequester(ZoomPhoneLoggingRequester):
    """Enable Airbyte's native HTTP cache for Zoom Phone parent/transcript requests."""

    use_cache: bool = True

    def __post_init__(self, parameters: Mapping[str, Any]) -> None:
        self.use_cache = True
        super().__post_init__(parameters)
