#
# Copyright (c) 2023 Airbyte, Inc., all rights reserved.
#

import base64
import logging
import re
import time
from calendar import monthrange
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta, timezone
from http import HTTPStatus
from importlib.metadata import PackageNotFoundError, version as package_version
from threading import Lock, Thread
from typing import Any, Callable, ClassVar, Iterable, Mapping, Optional, Union
from urllib.parse import urlsplit

import requests
from requests import HTTPError

from airbyte_cdk.models import AirbyteLogMessage, AirbyteMessage, Level, Type
from airbyte_cdk.sources.declarative.auth.declarative_authenticator import NoAuth
from airbyte_cdk.sources.declarative.interpolation import InterpolatedString
from airbyte_cdk.sources.declarative.migrations.state_migration import StateMigration
from airbyte_cdk.sources.declarative.extractors.record_extractor import RecordExtractor
from airbyte_cdk.sources.declarative.partition_routers.substream_partition_router import SafeResponse
from airbyte_cdk.sources.declarative.requesters.http_requester import HttpRequester
from airbyte_cdk.sources.declarative.types import Config


# https://developers.zoom.us/docs/internal-apps/s2s-oauth/#successful-response
# The Bearer token generated by server-to-server token will expire in one hour
BEARER_TOKEN_EXPIRES_IN = 3590



class SingletonMeta(type):
    _instances = {}

    def __call__(cls, *args, **kwargs):
        """
        Possible changes to the value of the `__init__` argument do not affect
        the returned instance.
        """
        if cls not in cls._instances:
            instance = super().__call__(*args, **kwargs)
            cls._instances[cls] = instance
        return cls._instances[cls]


@dataclass
class ServerToServerOauthAuthenticator(NoAuth):
    config: Config
    account_id: Union[InterpolatedString, str]
    client_id: Union[InterpolatedString, str]
    client_secret: Union[InterpolatedString, str]
    authorization_endpoint: Union[InterpolatedString, str]

    _instance = None
    _generate_token_time = 0
    _access_token = None
    _grant_type = "account_credentials"
    _token_lock: ClassVar[Lock] = Lock()

    def __post_init__(self, parameters: Mapping[str, Any]):
        self._account_id = InterpolatedString.create(self.account_id, parameters=parameters).eval(self.config)
        self._client_id = InterpolatedString.create(self.client_id, parameters=parameters).eval(self.config)
        self._client_secret = InterpolatedString.create(self.client_secret, parameters=parameters).eval(self.config)
        self._authorization_endpoint = InterpolatedString.create(self.authorization_endpoint, parameters=parameters).eval(self.config)

    def __call__(self, request: requests.PreparedRequest) -> requests.PreparedRequest:
        """Attach the page access token to params to authenticate on the HTTP request"""
        if self._access_token is None or ((time.time() - self._generate_token_time) > BEARER_TOKEN_EXPIRES_IN):
            with self._token_lock:
                if self._access_token is None or ((time.time() - self._generate_token_time) > BEARER_TOKEN_EXPIRES_IN):
                    self._access_token = self.generate_access_token()
        headers = {"Authorization": f"Bearer {self._access_token}", "Content-type": "application/json"}
        request.headers.update(headers)

        return request

    @property
    def auth_header(self) -> str:
        return "Authorization"

    @property
    def token(self) -> Optional[str]:
        return self._access_token if self._access_token else None

    def generate_access_token(self) -> str:
        self._generate_token_time = time.time()
        try:
            token = base64.b64encode(f"{self._client_id}:{self._client_secret}".encode("ascii")).decode("utf-8")
            headers = {"Authorization": f"Basic {token}", "Content-type": "application/json"}
            rest = requests.post(
                url=f"{self._authorization_endpoint}?grant_type={self._grant_type}&account_id={self._account_id}", headers=headers
            )
            if rest.status_code != HTTPStatus.OK:
                raise HTTPError(rest.text)
            return rest.json().get("access_token")
        except Exception as e:
            raise Exception(f"Error while generating access token: {e}") from e



@dataclass
class ZoomPhoneTranscriptStateMigration(StateMigration):
    """Repair transcript/timeline parent state for incremental parent traversal.

    The child cursor ``recording_date_time`` is copied directly from the
    ``phone_recordings.date_time`` parent record, so it is safe to use as the
    initial parent cursor when upgrading existing state that predates
    ``incremental_dependency: true``.
    """

    _logger: ClassVar[logging.Logger] = logging.getLogger("airbyte.phone_transcript_state")
    _parent_stream_name: ClassVar[str] = "phone_recordings"
    _parent_cursor_field: ClassVar[str] = "date_time"
    _child_cursor_field: ClassVar[str] = "recording_date_time"

    @classmethod
    def _candidate_parent_cursor(cls, stream_state: Mapping[str, Any]) -> tuple[Optional[Any], Optional[str]]:
        parent_state = stream_state.get("parent_state")
        if isinstance(parent_state, Mapping):
            phone_parent_state = parent_state.get(cls._parent_stream_name)
            if isinstance(phone_parent_state, Mapping):
                value = phone_parent_state.get(cls._parent_cursor_field)
                if value not in (None, ""):
                    return value, "parent_state"
                value = phone_parent_state.get(cls._child_cursor_field)
                if value not in (None, ""):
                    return value, "parent_state.recording_date_time"

        legacy_parent_state = stream_state.get(cls._parent_stream_name)
        if isinstance(legacy_parent_state, Mapping):
            value = legacy_parent_state.get(cls._parent_cursor_field)
            if value not in (None, ""):
                return value, "phone_recordings.date_time"
            value = legacy_parent_state.get(cls._child_cursor_field)
            if value not in (None, ""):
                return value, "phone_recordings.recording_date_time"

        global_state = stream_state.get("state")
        if isinstance(global_state, Mapping):
            value = global_state.get(cls._parent_cursor_field)
            if value not in (None, ""):
                return value, "state.date_time"
            value = global_state.get(cls._child_cursor_field)
            if value not in (None, ""):
                return value, "state.recording_date_time"

        value = stream_state.get(cls._parent_cursor_field)
        if value not in (None, ""):
            return value, "date_time"

        value = stream_state.get(cls._child_cursor_field)
        if value not in (None, ""):
            return value, "recording_date_time"

        return None, None

    @classmethod
    def _has_valid_parent_state(cls, stream_state: Mapping[str, Any]) -> bool:
        parent_state = stream_state.get("parent_state")
        if not isinstance(parent_state, Mapping):
            return False
        phone_parent_state = parent_state.get(cls._parent_stream_name)
        return (
            isinstance(phone_parent_state, Mapping)
            and phone_parent_state.get(cls._parent_cursor_field) not in (None, "")
        )

    def should_migrate(self, stream_state: Mapping[str, Any]) -> bool:
        if not stream_state or self._has_valid_parent_state(stream_state):
            return False
        cursor_value, _ = self._candidate_parent_cursor(stream_state)
        return cursor_value not in (None, "")

    def migrate(self, stream_state: Mapping[str, Any]) -> Mapping[str, Any]:
        cursor_value, source = self._candidate_parent_cursor(stream_state)
        if cursor_value in (None, ""):
            return stream_state

        migrated = dict(stream_state)
        existing_parent_state = migrated.get("parent_state")
        parent_state = dict(existing_parent_state) if isinstance(existing_parent_state, Mapping) else {}
        existing_phone_state = parent_state.get(self._parent_stream_name)
        phone_state = dict(existing_phone_state) if isinstance(existing_phone_state, Mapping) else {}
        phone_state[self._parent_cursor_field] = cursor_value
        parent_state[self._parent_stream_name] = phone_state
        migrated["parent_state"] = parent_state

        self._logger.info(
            "[phone_transcript_state] repaired_parent_state "
            f"parent={self._parent_stream_name} source={source} cursor={cursor_value}"
        )
        return migrated


@dataclass
class TimelineRecordExtractor(RecordExtractor):
    """Extract timeline entries and report whether Airbyte used lazy, cached HTTP, or network HTTP."""

    config: Config
    _summary_every: ClassVar[int] = 1000
    _logger: ClassVar[logging.Logger] = logging.getLogger("airbyte.phone_recording_transcript_timeline")
    _path_lock: Lock = field(default_factory=Lock, init=False, repr=False)
    _response_count: int = field(default=0, init=False, repr=False)
    _lazy_count: int = field(default=0, init=False, repr=False)
    _http_cache_count: int = field(default=0, init=False, repr=False)
    _http_network_count: int = field(default=0, init=False, repr=False)

    def _record_source_path(self, response: requests.Response) -> None:
        if isinstance(response, SafeResponse):
            source_path = "lazy"
        elif bool(getattr(response, "from_cache", False)):
            source_path = "http_cache"
        else:
            source_path = "http_network"

        summary = None
        with self._path_lock:
            self._response_count += 1
            if source_path == "lazy":
                self._lazy_count += 1
            elif source_path == "http_cache":
                self._http_cache_count += 1
            else:
                self._http_network_count += 1

            if self._response_count % self._summary_every == 0:
                summary = (
                    self._response_count,
                    self._lazy_count,
                    self._http_cache_count,
                    self._http_network_count,
                )

        if summary is not None:
            response_count, lazy_count, http_cache_count, http_network_count = summary
            lazy_pct = (lazy_count / response_count) * 100
            self._logger.info(
                "[phone_recording_transcript_timeline] "
                f"source_responses={response_count} "
                f"lazy={lazy_count} "
                f"http_cache={http_cache_count} "
                f"http_network={http_network_count} "
                f"lazy_pct={lazy_pct:.1f}%"
            )

    def extract_records(self, response: requests.Response) -> Iterable[Mapping[str, Any]]:
        self._record_source_path(response)

        try:
            payload = response.json()
        except (TypeError, ValueError):
            return

        if isinstance(payload, list):
            timeline = payload
        elif isinstance(payload, Mapping):
            timeline = payload.get("timeline")
        else:
            return

        if not isinstance(timeline, list):
            return

        for item in timeline:
            if isinstance(item, Mapping):
                yield dict(item)


@dataclass
class ZoomPhoneLoggingRequester(HttpRequester):
    """
    Adds compact Zoom Phone request telemetry without logging secrets, bodies,
    pagination token values, or resolved path IDs.
    """

    rate_limit_category: str = "UNKNOWN"
    history_limit_months: Optional[int] = None
    requester_role: str = "default"
    cache_name: Optional[str] = None
    _summary_every: ClassVar[int] = 200
    _periodic_summary_interval_seconds: ClassVar[int] = 300
    _periodic_summary_idle_grace_intervals: ClassVar[int] = 12
    _runtime_version_logged: ClassVar[bool] = False
    _runtime_version_lock: ClassVar[Lock] = Lock()
    _rate_limit_configs_logged: ClassVar[set[tuple[str, str]]] = set()
    _rate_limit_config_lock: ClassVar[Lock] = Lock()
    _request_count: int = field(default=0, init=False, repr=False)
    _cache_hit_count: int = field(default=0, init=False, repr=False)
    _total_duration_ms: int = field(default=0, init=False, repr=False)
    _history_limit_checked: bool = field(default=False, init=False, repr=False)
    _periodic_logger_started: bool = field(default=False, init=False, repr=False)
    _periodic_logger_lock: Lock = field(default_factory=Lock, init=False, repr=False)
    _metrics_lock: Lock = field(default_factory=Lock, init=False, repr=False)
    _active_http_request_count: int = field(default=0, init=False, repr=False)
    _last_activity_monotonic: float = field(default_factory=time.monotonic, init=False, repr=False)
    _parent_scan_started: bool = field(default=False, init=False, repr=False)
    _last_request_from: Optional[str] = field(default=None, init=False, repr=False)
    _last_request_to: Optional[str] = field(default=None, init=False, repr=False)
    _last_response_status: Optional[int] = field(default=None, init=False, repr=False)

    def __post_init__(self, parameters: Mapping[str, Any]) -> None:
        # Let Airbyte own the cache implementation. The optional alias only makes
        # requesters for the same endpoint share Airbyte's native cache namespace.
        display_name = self.name
        self.name = self.cache_name or display_name
        try:
            super().__post_init__(parameters)
        finally:
            self.name = display_name

        if not ZoomPhoneLoggingRequester._runtime_version_logged:
            with ZoomPhoneLoggingRequester._runtime_version_lock:
                if not ZoomPhoneLoggingRequester._runtime_version_logged:
                    try:
                        cdk_version = package_version("airbyte-cdk")
                    except PackageNotFoundError:
                        cdk_version = "unknown"
                    configured_workers = self.config.get("num_workers", 20)
                    light_rps = self.config.get("phone_light_requests_per_second", 20)
                    medium_rps = self.config.get("phone_medium_requests_per_second", 10)
                    heavy_rps = self.config.get("phone_heavy_requests_per_second", 5)
                    heavy_per_day = self.config.get("phone_heavy_requests_per_day", 15000)
                    self.logger.info(f"Runtime cdk={cdk_version} workers={configured_workers}")
                    self.logger.info(
                        "API budget "
                        f"light={light_rps}/s "
                        f"medium={medium_rps}/s "
                        f"heavy={heavy_rps}/s "
                        f"heavy_day={heavy_per_day}/day",
                    )
                    ZoomPhoneLoggingRequester._runtime_version_logged = True

        rate_config_key = (self.name, self.rate_limit_category)
        with ZoomPhoneLoggingRequester._rate_limit_config_lock:
            if rate_config_key not in ZoomPhoneLoggingRequester._rate_limit_configs_logged:
                self.logger.info(f"RateLimit [{self.name}] category={self.rate_limit_category}")
                ZoomPhoneLoggingRequester._rate_limit_configs_logged.add(rate_config_key)

    @staticmethod
    def _raw_value(value: Any) -> str:
        if isinstance(value, InterpolatedString):
            return value.string
        return str(value or "")

    def _safe_endpoint(self, url: str) -> str:
        raw_path = self._raw_value(self.path)
        if not raw_path:
            return urlsplit(url).path

        raw_base = self._raw_value(self.url_base)
        base_path = urlsplit(raw_base).path.rstrip("/") if raw_base else ""
        endpoint = f"{base_path}/{raw_path.lstrip('/')}"
        endpoint = re.sub(
            r"\{\{\s*([^{}]+?)\s*\}\}",
            lambda match: "{" + match.group(1).strip() + "}",
            endpoint,
        )
        return "/" + endpoint.lstrip("/")

    @staticmethod
    def _months_ago(months: int) -> date:
        today = datetime.now(timezone.utc).date()
        month_index = today.year * 12 + today.month - 1 - months
        year, zero_based_month = divmod(month_index, 12)
        month = zero_based_month + 1
        day = min(today.day, monthrange(year, month)[1])
        return date(year, month, day)

    def _check_history_limit(self) -> None:
        if (
            self._history_limit_checked
            or self.history_limit_months is None
        ):
            return

        self._history_limit_checked = True
        configured_start = self.config.get("phone_start_date")
        if not configured_start:
            return

        try:
            requested_start = date.fromisoformat(str(configured_start))
        except (TypeError, ValueError):
            return

        earliest_start = self._months_ago(self.history_limit_months) + timedelta(days=1)
        if requested_start < earliest_start:
            self.logger.warning(
                f"Notice [{self.name}] "
                f"requested_phone_start_date={requested_start.isoformat()} "
                f"exceeds_zoom_history_window={self.history_limit_months}m "
                f"effective_start_date={earliest_start.isoformat()}",
            )

    def _cache_metrics_enabled(self) -> bool:
        return self.use_cache

    def _record_request_metrics(self, duration_ms: int, from_cache: bool) -> int:
        with self._metrics_lock:
            self._request_count += 1
            self._total_duration_ms += duration_ms
            if from_cache:
                self._cache_hit_count += 1
            self._last_activity_monotonic = time.monotonic()
            return self._request_count

    def _emit_parent_log(self, level: Level, message: str) -> None:
        """Emit parent-stream logs through Airbyte's message repository.

        Parent requests run inside concurrent substream partition generation. Using
        the requester's MessageRepository ensures the log is forwarded through the
        ConcurrentMessageRepository/main Airbyte output queue instead of relying on
        ordinary Python logger propagation from that worker path.
        """
        self.message_repository.emit_message(
            AirbyteMessage(
                type=Type.LOG,
                log=AirbyteLogMessage(level=level, message=message),
            )
        )

    def _emit_info(self, message: str) -> None:
        if self.requester_role == "transcript_parent":
            self._emit_parent_log(Level.INFO, message)
        else:
            self.logger.info(message)

    def _emit_warning(self, message: str) -> None:
        if self.requester_role == "transcript_parent":
            self._emit_parent_log(Level.WARN, message)
        else:
            self.logger.warning(message)

    def _log_summary(self, periodic: bool = False) -> None:
        with self._metrics_lock:
            request_count = self._request_count
            cache_hit_count = self._cache_hit_count
            total_duration_ms = self._total_duration_ms
            active_http_requests = self._active_http_request_count
            last_activity_monotonic = self._last_activity_monotonic
            last_request_from = self._last_request_from
            last_request_to = self._last_request_to
            last_response_status = self._last_response_status

        average_duration_ms = (
            round(total_duration_ms / request_count) if request_count else 0
        )

        fields = [
            f"[{self.name}]",
            *(["(heartbeat)"] if periodic else []),
            f"role={self.requester_role}",
            f"requests={request_count}",
            f"active={active_http_requests}",
            f"avg_ms={average_duration_ms}",
        ]

        if periodic:
            seconds_since_activity = max(
                0, round(time.monotonic() - last_activity_monotonic)
            )
            fields.append(f"idle_s={seconds_since_activity}")

        if self._cache_metrics_enabled():
            cache_hit_rate = (
                (cache_hit_count / request_count) * 100 if request_count else 0.0
            )
            fields.extend(
                [
                    f"cache_hits={cache_hit_count}",
                    f"cache={cache_hit_rate:.1f}%",
                ]
            )

        if self.requester_role == "transcript_parent":
            if last_response_status is not None:
                fields.append(f"last_status={last_response_status}")
            if last_request_from is not None:
                fields.append(f"last_from={last_request_from}")
            if last_request_to is not None:
                fields.append(f"last_to={last_request_to}")

        self._emit_info(" ".join(fields))

    def _periodic_summary_loop(self) -> None:
        while True:
            time.sleep(self._periodic_summary_interval_seconds)

            with self._metrics_lock:
                request_count = self._request_count
                active_http_requests = self._active_http_request_count
                last_activity_monotonic = self._last_activity_monotonic

            if request_count == 0 and active_http_requests == 0:
                continue

            seconds_since_activity = time.monotonic() - last_activity_monotonic
            idle_grace_seconds = (
                self._periodic_summary_interval_seconds
                * self._periodic_summary_idle_grace_intervals
            )
            if active_http_requests == 0 and seconds_since_activity > idle_grace_seconds:
                continue

            self._log_summary(periodic=True)

    def _ensure_periodic_logger_started(self) -> None:
        if self._periodic_logger_started:
            return

        with self._periodic_logger_lock:
            if self._periodic_logger_started:
                return

            Thread(
                target=self._periodic_summary_loop,
                name=f"zoom-periodic-summary-{self.name}",
                daemon=True,
            ).start()
            self._periodic_logger_started = True

    def send_request(
        self,
        stream_state: Optional[Any] = None,
        stream_slice: Optional[Any] = None,
        next_page_token: Optional[Mapping[str, Any]] = None,
        path: Optional[str] = None,
        request_headers: Optional[Mapping[str, Any]] = None,
        request_params: Optional[Mapping[str, Any]] = None,
        request_body_data: Optional[Union[Mapping[str, Any], str]] = None,
        request_body_json: Optional[Mapping[str, Any]] = None,
        log_formatter: Optional[Callable[[requests.Response], Any]] = None,
    ) -> Optional[requests.Response]:
        self._check_history_limit()
        self._ensure_periodic_logger_started()
        with self._metrics_lock:
            self._active_http_request_count += 1
            self._last_activity_monotonic = time.monotonic()

        url = self._get_url(
            path=path,
            stream_state=stream_state,
            stream_slice=stream_slice,
            next_page_token=next_page_token,
        )
        endpoint = self._safe_endpoint(url)
        params = self._request_params(
            stream_state,
            stream_slice,
            next_page_token,
            request_params,
        )

        if self.requester_role == "transcript_parent":
            request_from = params.get("from")
            request_to = params.get("to")
            log_parent_start = False
            with self._metrics_lock:
                if request_from is not None:
                    self._last_request_from = str(request_from)
                if request_to is not None:
                    self._last_request_to = str(request_to)
                if not self._parent_scan_started:
                    self._parent_scan_started = True
                    log_parent_start = True
            if log_parent_start:
                fields = [f"[{self.name}]", "role=transcript_parent", "parent_scan=start"]
                if request_from is not None:
                    fields.append(f"from={request_from}")
                if request_to is not None:
                    fields.append(f"to={request_to}")
                self._emit_info(" ".join(fields))

        started = time.monotonic()

        try:
            response = super().send_request(
                stream_state=stream_state,
                stream_slice=stream_slice,
                next_page_token=next_page_token,
                path=path,
                request_headers=request_headers,
                request_params=request_params,
                request_body_data=request_body_data,
                request_body_json=request_body_json,
                log_formatter=log_formatter,
            )
        except Exception as exc:
            duration_ms = round((time.monotonic() - started) * 1000)
            self._emit_warning(
                f"Failed [{self.name}] "
                f"method={self.get_method().value} "
                f"endpoint={endpoint} "
                f"category={self.rate_limit_category} "
                f"duration_ms={duration_ms} "
                f"error={type(exc).__name__}"
            )
            raise
        finally:
            with self._metrics_lock:
                self._active_http_request_count = max(
                    0, self._active_http_request_count - 1
                )
                self._last_activity_monotonic = time.monotonic()

        duration_ms = round((time.monotonic() - started) * 1000)

        if response is None:
            self._emit_warning(
                f"Response [{self.name}] "
                f"method={self.get_method().value} "
                f"endpoint={endpoint} "
                f"category={self.rate_limit_category} "
                f"status=none "
                f"duration_ms={duration_ms}"
            )
            return response

        headers = response.headers
        from_cache = bool(getattr(response, "from_cache", False))
        request_count = self._record_request_metrics(duration_ms, from_cache)
        if self.requester_role == "transcript_parent":
            with self._metrics_lock:
                self._last_response_status = response.status_code

        fields = [
            f"[{self.name}]",
            f"method={self.get_method().value}",
            f"endpoint={endpoint}",
            f"category={self.rate_limit_category}",
            f"status={response.status_code}",
            f"duration_ms={duration_ms}",
        ]

        if self._cache_metrics_enabled():
            fields.append(f"cache_hit={from_cache}")

        if not from_cache:
            fields.append(f"http_ms={round(response.elapsed.total_seconds() * 1000)}")

        for key in ("from", "to", "recording_status", "page_size"):
            value = params.get(key)
            if value is not None:
                fields.append(f"{key}={value}")

        if next_page_token is not None:
            fields.append("continuation=true")

        zoom_headers = (
            ("zoom_category", "X-RateLimit-Category"),
            ("zoom_limit_type", "X-RateLimit-Type"),
            ("zoom_limit", "X-RateLimit-Limit"),
            ("zoom_remaining", "X-RateLimit-Remaining"),
            ("retry_after", "Retry-After"),
        )
        for label, header_name in zoom_headers:
            value = headers.get(header_name)
            if value is not None:
                fields.append(f"{label}={value}")

        message = " ".join(fields)
        if response.status_code == HTTPStatus.TOO_MANY_REQUESTS or response.status_code >= 500:
            self._emit_warning(message)

        if request_count % self._summary_every == 0:
            self._log_summary()

        return response


@dataclass
class ZoomPhoneCachedRequester(ZoomPhoneLoggingRequester):
    """Enable Airbyte's native HTTP cache before HttpRequester builds its HttpClient."""

    use_cache: bool = True

    def __post_init__(self, parameters: Mapping[str, Any]) -> None:
        self.use_cache = True
        super().__post_init__(parameters)
